export { default as ConveniencesIcon } from './alarm-clock-duotone.svg'
export { default as ActivitiesIcon } from './basketball-hoop-duotone.svg'
export { default as GuestServicesIcon } from './bell-concierge-duotone.svg'
export { default as MoreIcon } from './books-duotone.svg'
export { default as AccessibilityIcon } from './dog-leashed-duotone.svg'
export { default as FamilyIcon } from './family-duotone.svg'
export { default as OutdoorIcon } from './person-swimming-duotone.svg'
export { default as FoodAndDrinkIcon } from './pot-food-duotone.svg'
export { default as SpaIcon } from './spa-duotone.svg'
export { default as InternetIcon } from './wifi-duotone.svg'

export { default as Plane } from './plane-duotone.svg'
