export const poiCategoriesToInclude = [
  'airport',
  'amusement park',
  'theme park',
  'sports field',
  'beach',
  'casinos',
  'gaming',
  'lake',
  'landmark',
  'mountain',
  'museum',
  'concert hall',
  'natural park',
  'rail station',
  'train station',
  'tourism',
  'winery',
  'vineyard',
  'zoo',
  'aquarium',
  'wildlife sanctuary',
]
